AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: create movies table

Resources:
  ProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: learn-product-catalog
        KeySchema:
          -
            AttributeName: Id
            KeyType: HASH

        AttributeDefinitions:
          -
            AttributeName: Id
            AttributeType: N
          -
            AttributeName: Price
            AttributeType: N
          -
            AttributeName: ProductCategory
            AttributeType: S

        GlobalSecondaryIndexes:
          -
            IndexName: ProductCategory-Price-index
            KeySchema:
              -
                AttributeName: ProductCategory
                KeyType: HASH
              -
                AttributeName: Price
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5


        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        Tags:
          - Key: Team
            Value: Backend
          - Key: Project
            Value: Learn dynamodb
          - Key: AppType
            Value: Serverless
  MoviesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: learn-movies
        KeySchema:
          -
            AttributeName: year
            KeyType: HASH
          -
            AttributeName: title
            KeyType: RANGE

        AttributeDefinitions:
          -
            AttributeName: year
            AttributeType: N
          -
            AttributeName: title
            AttributeType: S

        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        Tags:
          - Key: Team
            Value: Backend
          - Key: Project
            Value: Learn dynamodb
          - Key: AppType
            Value: Serverless

  ForumTable:
    #https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template.html#serverless-sam-template-simpletable
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: learn-forum
      PrimaryKey:
        Name: Name
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  ThreadTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: learn-thread
        KeySchema:
          -
            AttributeName: ForumName
            KeyType: HASH
          -
            AttributeName: Subject
            KeyType: RANGE

        AttributeDefinitions:
          -
            AttributeName: ForumName
            AttributeType: S
          -
            AttributeName: Subject
            AttributeType: S

        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        Tags:
          - Key: Team
            Value: Backend
          - Key: Project
            Value: Learn dynamodb
          - Key: AppType
            Value: Serverless

  ReplyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: learn-reply
        KeySchema:
          -
            AttributeName: Id
            KeyType: HASH
          -
            AttributeName: ReplyDateTime
            KeyType: RANGE

        AttributeDefinitions:
          -
            AttributeName: Id
            AttributeType: S
          -
            AttributeName: ReplyDateTime
            AttributeType: S
          -
            AttributeName: PostedBy
            AttributeType: S
          -
            AttributeName: Message
            AttributeType: S

        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

        GlobalSecondaryIndexes:
          -
            IndexName: PostedBy-Price-index
            KeySchema:
              -
                AttributeName: PostedBy
                KeyType: HASH
              -
                AttributeName: Message
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        Tags:
          - Key: Team
            Value: Backend
          - Key: Project
            Value: Learn dynamodb
          - Key: AppType
            Value: Serverless